<?php

namespace AppBundle\Repository;

/**
 * CandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateRepository extends \Doctrine\ORM\EntityRepository
{
}
