<?php

namespace AppBundle\Repository;

/**
 * DistrictCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictCityRepository extends \Doctrine\ORM\EntityRepository
{
}
