<?php

namespace AppBundle\Repository;

/**
 * ElectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionRepository extends \Doctrine\ORM\EntityRepository
{
}
