<?php

namespace AppBundle\Repository;

/**
 * ElectionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
