<?php

namespace AppBundle\Repository;

/**
 * NuanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NuanceRepository extends \Doctrine\ORM\EntityRepository
{
}
