<?php

namespace AppBundle\Repository;

/**
 * ResultCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
