<?php

namespace AppBundle\Repository;

/**
 * ScoreCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
