<?php

namespace ElectionBundle\Repository;

/**
 * CandidacyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidacyRepository extends \Doctrine\ORM\EntityRepository
{
}
