<?php

namespace ElectionBundle\Repository;

/**
 * ElectionRoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionRoundRepository extends \Doctrine\ORM\EntityRepository
{
}
