<?php

namespace ElectionBundle\Repository;

/**
 * PoliticalNuanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoliticalNuanceRepository extends \Doctrine\ORM\EntityRepository
{
}
